language: node_js
node_js:
  - "0.10"
before_script: 'npm install -g istanbul && npm install -g mocha'
#script: 'istanbul cover _mocha -- -R spec test/spec'
#after_success: 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
script: 'istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec'
after_success: 'cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage'
